# Joining and Splitting Arrays
- concatenate
- stack
- split


In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5,6]])
a

array([[1, 2],
       [3, 4]])

In [3]:
b

array([[5, 6]])

In [4]:
together = np.concatenate((a,b), axis=0)

In [5]:
together

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
together.shape

(3, 2)

In [7]:
together[1,1] = 555

In [11]:
# together is a copy over a and b (not a view)
together

array([[  1,   2],
       [  3, 555],
       [  5,   6]])

In [9]:
a

array([[1, 2],
       [3, 4]])

In [10]:
b

array([[5, 6]])

In [13]:
c = np.array([[1, 2], [3,4]]) * 3 + 5
c

array([[ 8, 11],
       [14, 17]])

In [14]:
np.concatenate((a, c), axis=1)

array([[ 1,  2,  8, 11],
       [ 3,  4, 14, 17]])

In [22]:
np.concatenate((a, c), axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 8, 11],
       [14, 17]])

In [23]:
arrays = np.zeros((5,3,4))
for n in range(5):
    arrays[n] = np.random.randn(3, 4)
    
arrays

array([[[-2.05262866,  2.38215971,  0.19070119,  0.91367052],
        [ 0.37333193,  0.87790386,  1.01374444,  1.398094  ],
        [-1.392897  , -1.61215988,  0.60599049, -0.22690804]],

       [[-0.63436712,  0.52521597, -0.40944065, -1.04719493],
        [ 1.19873113, -0.51908893,  1.25136853,  1.00122099],
        [-2.57501094,  0.06815193,  0.9340568 ,  0.46954976]],

       [[ 0.34763827, -0.83496886,  0.24818077,  0.63615857],
        [ 0.53819209, -2.98468546,  0.58664415,  0.70741617],
        [-0.16340847,  1.09873721, -0.77299518,  1.1871334 ]],

       [[-0.42769995,  0.75273789, -0.03933575, -1.08045832],
        [ 0.42846239,  1.29151794,  1.28321307,  1.0054922 ],
        [-0.88205271,  0.04628397,  1.74456972, -0.31241681]],

       [[ 0.25396596,  1.21729339,  1.39193118,  1.21241688],
        [ 0.76486759,  0.87776964,  1.39873234,  0.65271729],
        [-0.39271077, -1.28943852,  0.75394783, -0.36901274]]])

In [24]:
stack0 = np.stack(arrays, axis=0)
stack1 = np.stack(arrays, axis=1)
stack2 = np.stack(arrays, axis=2)

In [25]:
stack0

array([[[-2.05262866,  2.38215971,  0.19070119,  0.91367052],
        [ 0.37333193,  0.87790386,  1.01374444,  1.398094  ],
        [-1.392897  , -1.61215988,  0.60599049, -0.22690804]],

       [[-0.63436712,  0.52521597, -0.40944065, -1.04719493],
        [ 1.19873113, -0.51908893,  1.25136853,  1.00122099],
        [-2.57501094,  0.06815193,  0.9340568 ,  0.46954976]],

       [[ 0.34763827, -0.83496886,  0.24818077,  0.63615857],
        [ 0.53819209, -2.98468546,  0.58664415,  0.70741617],
        [-0.16340847,  1.09873721, -0.77299518,  1.1871334 ]],

       [[-0.42769995,  0.75273789, -0.03933575, -1.08045832],
        [ 0.42846239,  1.29151794,  1.28321307,  1.0054922 ],
        [-0.88205271,  0.04628397,  1.74456972, -0.31241681]],

       [[ 0.25396596,  1.21729339,  1.39193118,  1.21241688],
        [ 0.76486759,  0.87776964,  1.39873234,  0.65271729],
        [-0.39271077, -1.28943852,  0.75394783, -0.36901274]]])

In [29]:
stack0.shape

(5, 3, 4)

In [30]:
stack1

array([[[-2.05262866,  2.38215971,  0.19070119,  0.91367052],
        [-0.63436712,  0.52521597, -0.40944065, -1.04719493],
        [ 0.34763827, -0.83496886,  0.24818077,  0.63615857],
        [-0.42769995,  0.75273789, -0.03933575, -1.08045832],
        [ 0.25396596,  1.21729339,  1.39193118,  1.21241688]],

       [[ 0.37333193,  0.87790386,  1.01374444,  1.398094  ],
        [ 1.19873113, -0.51908893,  1.25136853,  1.00122099],
        [ 0.53819209, -2.98468546,  0.58664415,  0.70741617],
        [ 0.42846239,  1.29151794,  1.28321307,  1.0054922 ],
        [ 0.76486759,  0.87776964,  1.39873234,  0.65271729]],

       [[-1.392897  , -1.61215988,  0.60599049, -0.22690804],
        [-2.57501094,  0.06815193,  0.9340568 ,  0.46954976],
        [-0.16340847,  1.09873721, -0.77299518,  1.1871334 ],
        [-0.88205271,  0.04628397,  1.74456972, -0.31241681],
        [-0.39271077, -1.28943852,  0.75394783, -0.36901274]]])

In [31]:
stack1.shape

(3, 5, 4)

In [32]:
stack2

array([[[-2.05262866, -0.63436712,  0.34763827, -0.42769995,
          0.25396596],
        [ 2.38215971,  0.52521597, -0.83496886,  0.75273789,
          1.21729339],
        [ 0.19070119, -0.40944065,  0.24818077, -0.03933575,
          1.39193118],
        [ 0.91367052, -1.04719493,  0.63615857, -1.08045832,
          1.21241688]],

       [[ 0.37333193,  1.19873113,  0.53819209,  0.42846239,
          0.76486759],
        [ 0.87790386, -0.51908893, -2.98468546,  1.29151794,
          0.87776964],
        [ 1.01374444,  1.25136853,  0.58664415,  1.28321307,
          1.39873234],
        [ 1.398094  ,  1.00122099,  0.70741617,  1.0054922 ,
          0.65271729]],

       [[-1.392897  , -2.57501094, -0.16340847, -0.88205271,
         -0.39271077],
        [-1.61215988,  0.06815193,  1.09873721,  0.04628397,
         -1.28943852],
        [ 0.60599049,  0.9340568 , -0.77299518,  1.74456972,
          0.75394783],
        [-0.22690804,  0.46954976,  1.1871334 , -0.31241681,
         -0

In [33]:
stack2.shape

(3, 4, 5)

In [34]:
temp = np.arange(5)
np.split(temp, 0)

ZeroDivisionError: integer division or modulo by zero

In [35]:
np.split(temp, 1)

[array([0, 1, 2, 3, 4])]

In [36]:
before_split = stack0
before_split.shape

(5, 3, 4)

In [37]:
s0 = np.split(before_split, 5, axis=0)
s0

[array([[[-2.05262866,  2.38215971,  0.19070119,  0.91367052],
         [ 0.37333193,  0.87790386,  1.01374444,  1.398094  ],
         [-1.392897  , -1.61215988,  0.60599049, -0.22690804]]]),
 array([[[-0.63436712,  0.52521597, -0.40944065, -1.04719493],
         [ 1.19873113, -0.51908893,  1.25136853,  1.00122099],
         [-2.57501094,  0.06815193,  0.9340568 ,  0.46954976]]]),
 array([[[ 0.34763827, -0.83496886,  0.24818077,  0.63615857],
         [ 0.53819209, -2.98468546,  0.58664415,  0.70741617],
         [-0.16340847,  1.09873721, -0.77299518,  1.1871334 ]]]),
 array([[[-0.42769995,  0.75273789, -0.03933575, -1.08045832],
         [ 0.42846239,  1.29151794,  1.28321307,  1.0054922 ],
         [-0.88205271,  0.04628397,  1.74456972, -0.31241681]]]),
 array([[[ 0.25396596,  1.21729339,  1.39193118,  1.21241688],
         [ 0.76486759,  0.87776964,  1.39873234,  0.65271729],
         [-0.39271077, -1.28943852,  0.75394783, -0.36901274]]])]

In [38]:
type(s0)

list

In [39]:
s0[1]

array([[[-0.63436712,  0.52521597, -0.40944065, -1.04719493],
        [ 1.19873113, -0.51908893,  1.25136853,  1.00122099],
        [-2.57501094,  0.06815193,  0.9340568 ,  0.46954976]]])

In [40]:
s0[1].shape

(1, 3, 4)

In [41]:
s1 = np.split(before_split, 3, axis=1)
s1

[array([[[-2.05262866,  2.38215971,  0.19070119,  0.91367052]],
 
        [[-0.63436712,  0.52521597, -0.40944065, -1.04719493]],
 
        [[ 0.34763827, -0.83496886,  0.24818077,  0.63615857]],
 
        [[-0.42769995,  0.75273789, -0.03933575, -1.08045832]],
 
        [[ 0.25396596,  1.21729339,  1.39193118,  1.21241688]]]),
 array([[[ 0.37333193,  0.87790386,  1.01374444,  1.398094  ]],
 
        [[ 1.19873113, -0.51908893,  1.25136853,  1.00122099]],
 
        [[ 0.53819209, -2.98468546,  0.58664415,  0.70741617]],
 
        [[ 0.42846239,  1.29151794,  1.28321307,  1.0054922 ]],
 
        [[ 0.76486759,  0.87776964,  1.39873234,  0.65271729]]]),
 array([[[-1.392897  , -1.61215988,  0.60599049, -0.22690804]],
 
        [[-2.57501094,  0.06815193,  0.9340568 ,  0.46954976]],
 
        [[-0.16340847,  1.09873721, -0.77299518,  1.1871334 ]],
 
        [[-0.88205271,  0.04628397,  1.74456972, -0.31241681]],
 
        [[-0.39271077, -1.28943852,  0.75394783, -0.36901274]]])]

In [42]:
s2 = np.split(before_split, 4, axis=2)
s2

[array([[[-2.05262866],
         [ 0.37333193],
         [-1.392897  ]],
 
        [[-0.63436712],
         [ 1.19873113],
         [-2.57501094]],
 
        [[ 0.34763827],
         [ 0.53819209],
         [-0.16340847]],
 
        [[-0.42769995],
         [ 0.42846239],
         [-0.88205271]],
 
        [[ 0.25396596],
         [ 0.76486759],
         [-0.39271077]]]), array([[[ 2.38215971],
         [ 0.87790386],
         [-1.61215988]],
 
        [[ 0.52521597],
         [-0.51908893],
         [ 0.06815193]],
 
        [[-0.83496886],
         [-2.98468546],
         [ 1.09873721]],
 
        [[ 0.75273789],
         [ 1.29151794],
         [ 0.04628397]],
 
        [[ 1.21729339],
         [ 0.87776964],
         [-1.28943852]]]), array([[[ 0.19070119],
         [ 1.01374444],
         [ 0.60599049]],
 
        [[-0.40944065],
         [ 1.25136853],
         [ 0.9340568 ]],
 
        [[ 0.24818077],
         [ 0.58664415],
         [-0.77299518]],
 
        [[-0.03933575],
   

In [ ]:
rpepato