<h1>Linear Algebra</h1>

In [1]:
import numpy as np

In [2]:
my_first_matrix = np.matrix([[3, 1, 4], [1, 5, 9], [2, 6, 5]])
my_first_matrix

matrix([[3, 1, 4],
        [1, 5, 9],
        [2, 6, 5]])

In [3]:
my_first_matrix.T

matrix([[3, 1, 2],
        [1, 5, 6],
        [4, 9, 5]])

In [4]:
my_first_matrix.I

matrix([[ 0.32222222, -0.21111111,  0.12222222],
        [-0.14444444, -0.07777778,  0.25555556],
        [ 0.04444444,  0.17777778, -0.15555556]])

In [5]:
my_first_matrix * my_first_matrix.I

matrix([[1.00000000e+00, 1.11022302e-16, 0.00000000e+00],
        [5.55111512e-17, 1.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 1.11022302e-16, 1.00000000e+00]])

In [6]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Solve simultaneous linear equations

In [7]:
right_hand_side = np.matrix([[11], [22], [33]])

In [8]:
my_first_inverse = my_first_matrix.I

In [9]:
solution = my_first_inverse * right_hand_side

In [10]:
solution

matrix([[ 2.93333333],
        [ 5.13333333],
        [-0.73333333]])

In [11]:
solution[0]

matrix([[2.93333333]])

In [12]:
my_first_matrix * solution - right_hand_side

matrix([[0.00000000e+00],
        [0.00000000e+00],
        [7.10542736e-15]])

In [13]:
# more efficient for large matrices
from numpy.linalg import solve
solve(my_first_matrix, right_hand_side)

matrix([[ 2.93333333],
        [ 5.13333333],
        [-0.73333333]])

In [15]:
# Compute  the eigenvalues and right eigenvectors
from numpy.linalg import eig
eig(my_first_matrix)

(array([13.08576474,  2.58000566, -2.66577041]),
 matrix([[-0.31542644, -0.95117074, -0.32372474],
         [-0.72306109,  0.30781323, -0.70222933],
         [-0.61456393,  0.02291827,  0.63409484]]))