# Array Shape Manipulation

In [1]:
import numpy as np

### reshape
from: http://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html#numpy.reshape

NOTE: This will be a new view object if possible; otherwise, it will be a copy.

In [2]:
my_start_array = np.array(np.arange(24))
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [3]:
my_start_array.shape

(24,)

In [4]:
my_3_8_array = my_start_array.reshape((3, 8))
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [5]:
my_3_8_array[0,0] = 1234

In [7]:
# my_3_8_array is a view or a copy of my_start_array
my_start_array

array([1234,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

In [8]:
my_ravel_array = my_3_8_array.ravel()

In [9]:
my_ravel_array

array([1234,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

In [11]:
my_ravel_array.shape

(24,)

In [12]:
for i in my_3_8_array.flat:
    print(i)

1234
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [13]:
y = np.arange(60).reshape(-1, 2, 3)

In [14]:
y.shape

(10, 2, 3)

In [15]:
y

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41]],

       [[42, 43, 44],
        [45, 46, 47]],

       [[48, 49, 50],
        [51, 52, 53]],

       [[54, 55, 56],
        [57, 58, 59]]])

In [16]:
k = y.ravel()

In [17]:
k

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [18]:
for i in y.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
