# Brain Teasers
for more brain teasers, please see: http://www.labri.fr/perso/nrougier/teaching/numpy.100/index.html

In [1]:
import numpy as np
np.set_printoptions(precision=2)

### What version of NumPy are you using?

In [2]:
np.__version__

'1.16.2'

### Display array elements in reverse order

In [7]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.flip(a)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [10]:
# another possible solution
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Triple elements in array

In [6]:
a * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57])

### Create array with 20 zeros; every fifth element equals four

In [24]:
zeros = np.zeros(20)
zeros[0:19:5] = 4
zeros

array([4., 0., 0., 0., 0., 4., 0., 0., 0., 0., 4., 0., 0., 0., 0., 4., 0.,
       0., 0., 0.])

In [21]:
# another possible solution
zeros = np.zeros(20)
zeros[0::5] = 4
zeros

array([4., 0., 0., 0., 0., 4., 0., 0., 0., 0., 4., 0., 0., 0., 0., 4., 0.,
       0., 0., 0.])

### Transpose the rows and columns

In [26]:
my_matrix = np.matrix(np.array(np.arange(9)).reshape(3,3))
my_matrix

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [27]:
my_matrix.T

matrix([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

### Create a 5x5 identity matrix with integer components

In [29]:
matrix = np.asmatrix(np.eye(5, dtype='int64'))
matrix

matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

### Find the mean of a vector with 30 random elements.  Can you guess the approximate value for the mean?

In [33]:
v = np.random.random(30)
v.mean()

0.5154546683944816

#### Repeat, and visually estimate the mean for the sum of the two means

In [36]:
v = np.random.random(30)
v.mean()

0.46133450245870655

#### Repeat, and visually estimate the mean for the sum of the two means

In [37]:
v = np.random.random(30)
v.mean()

0.47790874745930395

### Create an 8x8 checker board with alternating zeros and ones

In [39]:
board = np.zeros((8,8), dtype='int64')
board[1::2, ::2] = 1
board[::2, 1::2] = 1
board

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### Create a sorted vector that contain 'n' random numbers

In [61]:
n = 20
v = np.random.random(n)
s = np.sort(v)
s


array([0.03, 0.03, 0.04, 0.11, 0.16, 0.33, 0.33, 0.36, 0.39, 0.39, 0.44,
       0.5 , 0.59, 0.66, 0.71, 0.73, 0.83, 0.89, 0.93, 0.93])

### Without sorting, replace largest element in random array with the value 1234

In [81]:
ra = np.random.randint(0, 1000, 20)
ra

array([772, 259,  29, 730, 115, 810, 943, 812, 462, 146, 542, 890, 700,
       462, 891, 794, 406, 974, 258, 649])

In [82]:
indexes = np.argmax(ra)
indexes

17

In [83]:
ra[indexes] = 1234
ra

array([ 772,  259,   29,  730,  115,  810,  943,  812,  462,  146,  542,
        890,  700,  462,  891,  794,  406, 1234,  258,  649])

In [86]:
# another possible solution
v[v.argmax()] = 1234
v

array([7.30e-01, 6.63e-01, 8.25e-01, 1.23e+03, 5.04e-01, 3.90e-01,
       7.10e-01, 3.91e-01, 8.86e-01, 9.28e-01, 3.55e-02, 4.43e-01,
       3.57e-01, 3.33e-02, 1.64e-01, 1.08e-01, 3.26e-01, 3.32e-01,
       2.90e-02, 5.92e-01])

### Given the following data type and data set; sort according to 'height'

source: http://docs.scipy.org/doc/numpy/reference/generated/numpy.sort.html

In [87]:
camelot_dtype = [('name', 'S10'), ('height', float), ('age', int)]
camelot_values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)]

In [91]:
camelot_array = np.array(camelot_values, dtype=camelot_dtype)
np.sort(camelot_array, order='height')

array([(b'Galahad', 1.7, 38), (b'Arthur', 1.8, 41),
       (b'Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

### Make an array read-only (immutable)

In [92]:
i = np.arange(10)
i.flags.writeable = False

### Print enumerated values from a 3x3 NumPy array

In [95]:
ea = np.random.random((3,3))
for i, v in np.ndenumerate(ea):
    print(i, v)

(0, 0) 0.7958847869218387
(0, 1) 0.08118664145755095
(0, 2) 0.33356565492641077
(1, 0) 0.548937803094752
(1, 1) 0.5539943814715009
(1, 2) 0.675920720251678
(2, 0) 0.3552537849366061
(2, 1) 0.7860492825558639
(2, 2) 0.7850522656089582
